/**
 * j_com_badlogic_gdx_backends_iosrobovm_IOSInput$HiddenTextField.m
 *
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * It is used to provide Java class visibility to IntefaceBuilder
 * DO NOT MODIFY! DO NOT ADD UNDER VERSION CONTROL
 */

#import "j_com_badlogic_gdx_backends_iosrobovm_IOSInput$HiddenTextField.h"

@implementation j_com_badlogic_gdx_backends_iosrobovm_IOSInput$HiddenTextField

@end
