/**
 * j_var3d_net_center_ios_VIOSLauncher$VUITextField.h
 *
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * It is used to provide Java class visibility to IntefaceBuilder
 * DO NOT MODIFY! DO NOT ADD UNDER VERSION CONTROL
 */

@interface j_var3d_net_center_ios_VIOSLauncher$VUITextField : UITextField

@end
